global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "simple_server"
    static_configs:
      - targets: ["host.docker.internal:8081"] # Use this for localhost from Docker
